# Generated by Django 4.2.16 on 2026-04-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_task_is_active'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='core_activi_board_i_d7686e_idx',
            old_name='core_activi_board_i_fa7b2a_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='core_activi_created_5c6490_idx',
            old_name='core_activi_created_dcb2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='core_task_board_i_87654a_idx',
            old_name='core_task_board_i_cf5638_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='core_task_column__4ac428_idx',
            old_name='core_task_column__1a8ba5_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='core_task_order_880fed_idx',
            old_name='core_task_order_dcd4be_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
